import {
  BarChart3,
  Bell,
  Bike,
  Banknote,
  BookOpen,
  Briefcase,
  CalendarCheck,
  Car,
  Circle,
  Coffee,
  Cpu,
  CreditCard,
  Download,
  Dumbbell,
  Euro,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartHandshake,
  HeartPulse,
  Home,
  Info,
  LayoutDashboard,
  LineChart,
  ListChecks,
  Music,
  Moon,
  Landmark,
  PiggyBank,
  PlusCircle,
  Repeat,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Shirt,
  ShoppingBasket,
  Sparkles,
  Sun,
  Target,
  Train,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  Utensils,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

const icons: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  income: TrendingUp,
  expenses: TrendingDown,
  budgets: ListChecks,
  goals: Target,
  projection: LineChart,
  reminders: Bell,
  settings: Settings,
  wallet: Wallet,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  'heart-handshake': HeartHandshake,
  'line-chart': LineChart,
  'plus-circle': PlusCircle,
  utensils: Utensils,
  coffee: Coffee,
  'shopping-basket': ShoppingBasket,
  train: Train,
  sparkles: Sparkles,
  music: Music,
  'gamepad-2': Gamepad2,
  cpu: Cpu,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  bike: Bike,
  car: Car,
  shirt: Shirt,
  briefcase: Briefcase,
  'heart-pulse': HeartPulse,
  dumbbell: Dumbbell,
  repeat: Repeat,
  home: Home,
  gift: Gift,
  circle: Circle,
  euro: Euro,
  card: CreditCard,
  alert: ShieldAlert,
  shield: ShieldCheck,
  info: Info,
  moon: Moon,
  sun: Sun,
  upload: Upload,
  download: Download,
  trash: Trash2,
  calendar: CalendarCheck,
  chart: BarChart3,
};

export const financeIconOptions = [
  { name: 'briefcase', label: 'Arbeit' },
  { name: 'graduation-cap', label: 'Uni' },
  { name: 'book-open', label: 'Lernen' },
  { name: 'utensils', label: 'Essen' },
  { name: 'coffee', label: 'Cafe' },
  { name: 'shirt', label: 'Kleidung' },
  { name: 'sparkles', label: 'Freizeit' },
  { name: 'music', label: 'Musik' },
  { name: 'gamepad-2', label: 'Gaming' },
  { name: 'repeat', label: 'Transfer' },
  { name: 'wallet', label: 'Geld' },
  { name: 'banknote', label: 'Cash' },
  { name: 'piggy-bank', label: 'Sparen' },
  { name: 'car', label: 'Auto' },
  { name: 'bike', label: 'Motorrad' },
  { name: 'train', label: 'Transport' },
  { name: 'gift', label: 'Geschenk' },
  { name: 'heart-pulse', label: 'Gesundheit' },
  { name: 'dumbbell', label: 'Fitness' },
  { name: 'cpu', label: 'Technik' },
  { name: 'home', label: 'Wohnen' },
  { name: 'line-chart', label: 'Invest' },
  { name: 'circle', label: 'Neutral' },
];

export const FinanceIcon = ({
  name,
  className,
  size = 18,
}: {
  name: string;
  className?: string;
  size?: number;
}) => {
  const Icon = icons[name] ?? Circle;
  return <Icon aria-hidden="true" className={className} size={size} strokeWidth={2} />;
};
